---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(polite)
library(rvest)

provinces <- c("British Columbia", "Alberta", "Saskatchewan", "Manitoba", "Ontario", "Québec", "New Brunswick", "Prince Edward Island", "Nova Scotia", "Newfoundland and Labrador", "Yukon", "Northwest Territories")  
  

url <- "https://news.mcdonalds.ca/covid-19-tracker/"

bow(url)

scrape <- scrape(bow(url))

scrape_result <- scrape %>% 
  html_table(fill = TRUE) 

datasets <- map(scrape_result, as_tibble, .name_repair = "minimal")
#datasets[[2]][9,3] = datasets[[2]][9,4]

shuffle_along <- function(x){
  y <- x %>% 
    janitor::clean_names() %>% 
    mutate(details = 
             if_else(!str_detect(details, "Positive"), location, details))
  return(y)
}

get_3 <- function(x){
  y <- x %>% 
    select(1:3)
    return(y)
}

n_col <- unlist(lapply(datasets, ncol))
moved <- lapply(datasets[n_col > 2], shuffle_along) 
three_col <- lapply(moved, get_3) 

maccas <- bind_rows(three_col, .id = "id") %>% 
  mutate(id = parse_number(id)) %>% 
  mutate(province = provinces[id]) %>% 
  select(-id)

write_csv(maccas, "2021-01-20_mcdonalds-employees-covid.csv")

```

```{r}
# https://stackoverflow.com/questions/29421436/adding-provinces-to-canadian-map-in-r

library(rgdal)

if (!file.exists("./src/ref/ne_50m_admin_1_states_provinces_lakes/ne_50m_admin_1_states_provinces_lakes.dbf")){
  download.file(file.path('http://www.naturalearthdata.com/http/',
                          'www.naturalearthdata.com/download/50m/cultural',
                          'ne_50m_admin_1_states_provinces_lakes.zip'), 
                f <- tempfile())
  unzip(f, exdir = "./src/ref/ne_50m_admin_1_states_provinces_lakes")
  rm(f)
}

region <- readOGR("./src/ref/ne_50m_admin_1_states_provinces_lakes", 'ne_50m_admin_1_states_provinces_lakes', encoding='UTF-8')

regions <- subset(region, name %in% c("British Columbia", "Alberta", "Saskatchewan", "Manitoba", "Ontario", "Québec", "New Brunswick", "Prince Edward Island", "Nova Scotia", "Newfoundland and Labrador", "Yukon", "Northwest Territories", "Nunavut")) # region is defined in the first part of the code (see above)

saveRDS(sf::st_as_sf(regions), "inst/tutorials/w2_class/data/canada_provinces.RDS")

```
